### ISSUE TITLE
Contribute to Typings Registry

### ISSUE THREAD

**Issue by thed0ctor** [JasonKleban/Framework7.d.ts#1]
Could you contribute this to the [Typings registry ](https://github.com/typings/registry) so that it can be installed as a Typings package?

**Comment by JasonKleban** [comment]
#3 takes care of it?

**Comment by aldahick** [comment]
That was the intent, yes.

**Comment by aldahick** [comment]
Well, actually, #3 makes it possible. I don't think the Typings people allow non-contributors to add a package to the registry - that is, the author of the definitions (@JasonKleban) would have to actually contribute them to the registry. Would you be willing to do that?

**Comment by AbraaoAlves** [comment]
Sorry to ask here @aldahick, but...
Why can't found framework7 via typings-cli, like this:

``` bash
typings search framework7
```

**Comment by JasonKleban** [comment]
@aldahick - getting it prepared and into the typings registry seems like a pain in the butt.  But this is MIT license so I think that clears anybody to copy it into there if they want to.
