### ISSUE TITLE
Definitely Typed

### ISSUE THREAD

**Issue by larrybahr** [JasonKleban/Framework7.d.ts#12]
Could you add the Framework7 definition to DefinitelyTyped? This would be very helpful and make it easier to use in projects.
https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by larrybahr** [comment]
It looks like at least one other person would like this as well.
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/4016

**Comment by JasonKleban** [comment]
Hi @larrybahr please see https://github.com/JasonKleban/Framework7.d.ts/issues/1
