### ISSUE TITLE
V2 Soon

### ISSUE THREAD

**Issue by ZanderBrown** [JasonKleban/Framework7.d.ts#16]
Just a note to insure you are aware that a V2 API breaking update is due to be released soon, congratulations on a great project.

I've used you project on many occasions and it's a shame we can't offer typings upstream.

V2 is based in ES6 (and transpiled) so you should be easier to produce typings for.

**Comment by JasonKleban** [comment]
Sounds great!  Is there any documentation for it yet from which to infer the typings?  I see that there's a lot of work on v2 but I can't find any documentation on what has changed, philosophically or otherwise.

**Comment by ZanderBrown** [comment]
Unfortunately we haven't quite settled on things yet, however a release with docs is planned soon.

**Comment by JasonKleban** [comment]
Well I think everyone would benefit from the type definitions being shipped with framework7.  Seems like you're part of that project so feel free to take them.  I'll help too if I can.

**Comment by seiryokusan** [comment]
Hey, 
Since V2 is out now, is there any update on this issue?
Thanks !

**Comment by JasonKleban** [comment]
It isn’t out yet and I don’t see any docs to infer the types from.  I’ve asked but I’ve gotten no response yet.

**Comment by JasonKleban** [comment]
A v2 branch is started!  https://github.com/JasonKleban/Framework7.d.ts/tree/v2

**Comment by JasonKleban** [comment]
v3 is started.  See the readme
