### ISSUE TITLE
NotificationOptions is missing message

### ISSUE THREAD

**Issue by czb** [JasonKleban/Framework7.d.ts#19]
`interface NotificationOptions {` should contain `message?: string;`

**Comment by JasonKleban** [comment]
Sure!  Make a PR?

**Comment by czb** [comment]
will do soon :) shall I make PR to this repo?

**Comment by JasonKleban** [comment]
Yeah, so afaik the normal process is to fork it to your own account here on the github, make a new branch for your fix, clone all *that* to your local, make the changes, push back to github, and you get the option to submit a PR there.

**Comment by jdspugh** [comment]
I fixed this issue. It's merged already.
