### ISSUE TITLE
How to get this working with Framework7-Vue

### ISSUE THREAD

**Issue by timmtim** [JasonKleban/Framework7.d.ts#28]
I'm working on the V2 branch. It is possible to get Framework7-Vue also working? Can you point me in the right direction?

**Comment by JasonKleban** [comment]
Cool!  Have you seen https://github.com/JasonKleban/framework7-vue.d.ts  ?

**Comment by JasonKleban** [comment]
See my readme now for v3.  Not _great_ news for you perhaps.
