### ISSUE TITLE
Framework7 v3

### ISSUE THREAD

**Issue by J05HI** [JasonKleban/Framework7.d.ts#31]
@JasonKleban 
Have you planned them for v3 too?

**Comment by J05HI** [comment]
@JasonKleban
I've created an issue in the F7 repo and I got the answer that they'll add it soon.

**Comment by JasonKleban** [comment]
I've started a v3.  Can you share with me the issue you opened?  Maybe my work is unnecessary.

**Comment by nolimits4web** [comment]
Hey @JasonKleban 

For React/Vue components we use [Phenome.js](http://phenomejs.org/), the tool that auto generate/compile components to React/Vue components. And we have in plans to add automatic TypeScript definitions compilation too https://github.com/phenomejs/phenome/issues/11.

So your work on typedefs for React and Vue components can be unnecessary. Would be better if you can help us to add ts support to Phenome and we will have defs for all components at once 😉
